### PR TITLE
Stream / Async Generator Conversions

### PR DESCRIPTION
**Pull request by awestlake87**
I've pushed both versions of `into_stream` as `into_stream_v1` and `into_stream_v2`. I'd like to get some benchmarks for each of these versions + make them public for other contributors to comment on.

Streams as Async Generators could also be included in this PR later on.

### CODE REVIEW

**Comment by wfxr** [comment]
Hi @awestlake87 Does this pr still work in progress ?

**Comment by awestlake87** [comment]
In a way, yeah. It worked in 0.13, but the person who requested it ended up not needing it, so I figured I'd hold off on integrating it into the library until I got a better impression about whether it was needed or not. In general I like to know at least one person is using it so I might get some feedback if it needs improvement / fixing.

If you want, I can update this branch to the latest version so you can try it out in your project!

**Comment by wfxr** [comment]
@awestlake87 Thanks for maintaining this awesome lib!

I currently use `pyo3-asyncio` to implement a python client for our feature store, which is a wrapper of [tonic](https://github.com/hyperium/tonic) rpc client that uses async stream to communicate with the rpc server. I tried and found it hard to convert python's iterator to async stream. It would be very helpful for us if you could update this.

**Comment by awestlake87** [comment]
Ok, I'll try to get that updated sometime after work this evening (CST).

**Comment by awestlake87** [comment]
Alright, these should be good to go for 0.15 now if you want to try them out. The docs for these conversions are virtually non-existent at the moment, but the tests should give you a good example of how to use them:

```rust
const TOKIO_TEST_MOD: &str = r#"
import asyncio 

async def gen():
    for i in range(10):
        await asyncio.sleep(0.1)
        yield i        
"#;

#[pyo3_asyncio::tokio::test]
async fn test_async_gen_v1() -> PyResult<()> {
    let stream = Python::with_gil(|py| {
        let test_mod = PyModule::from_code(
            py,
            TOKIO_TEST_MOD,
            "test_rust_coroutine/tokio_test_mod.py",
            "tokio_test_mod",
        )?;

        pyo3_asyncio::tokio::into_stream_v1(test_mod.call_method0("gen")?)
    })?;

    let vals = stream
        .map(|item| Python::with_gil(|py| -> PyResult<i32> { Ok(item?.as_ref(py).extract()?) }))
        .try_collect::<Vec<i32>>()
        .await?;

    assert_eq!((0..10).collect::<Vec<i32>>(), vals);

    Ok(())
}

#[pyo3_asyncio::tokio::test]
async fn test_async_gen_v2() -> PyResult<()> {
    let stream = Python::with_gil(|py| {
        let test_mod = PyModule::from_code(
            py,
            TOKIO_TEST_MOD,
            "test_rust_coroutine/tokio_test_mod.py",
            "tokio_test_mod",
        )?;

        pyo3_asyncio::tokio::into_stream_v2(test_mod.call_method0("gen")?)
    })?;

    let vals = stream
        .map(|item| Python::with_gil(|py| -> PyResult<i32> { Ok(item.as_ref(py).extract()?) }))
        .try_collect::<Vec<i32>>()
        .await?;

    assert_eq!((0..10).collect::<Vec<i32>>(), vals);

    Ok(())
}
```

Aside from minor return type differences, v1 has a simpler implementation under the hood while v2 is more complex but should be more performant. I never got around to any real benchmarks with them though, so your experience may differ.

Let me know if you have any questions / feedback!

**Comment by wfxr** [comment]
@awestlake87 Great! I will try it these days after I'm done with some urgent things.

**Comment by wfxr** [comment]
@awestlake87 Sorry for the late reply. I've been on vacation for the past few weeks.

I have tried these apis. Both `v1` and `v2` work well. I'm excited to see it released in the next version.

I also wonder if there will be a mirror api `into_iterator` to convert rust `async stream` into python `async iterator` ?

**Comment by awestlake87** [comment]
Yeah, there's definitely a place for a `stream_into_py` conversion. I haven't taken a look at implementing it yet so far, but we should probably support the inverse at some point.

**Pull request merged**
