### PR TITLE
Bump PyO3 to 0.20

### PR DESCRIPTION
**Pull request by awestlake87**
- [x] Bump PyO3 version (thanks @gi0baro)
- [x] Bump MSRV? (now 1.63)
- [x] Merge #92 
- [ ] ~~Intern strings? #106~~ (postponed)
- [ ] ~~Update clap and syn?~~ (postponed)
- [x] Update Docs

### CODE REVIEW

**Comment by sslivkoff** [comment]
hi there. it would be great to get this merged for PyO3 0.20, as it enables python3.12 compatibility

do you think these last two items should be in the 0.20 version or do you think it's ready to merge as is?

**Comment by cjdsellers** [comment]
There's the option we could merge as is, and the performance improvements could become a patch release when bandwidth is available?

**Comment by awestlake87** [comment]
Yeah sorry, between work and family I haven't given this project much time lately. This project needs a bit of maintenance, and I'll just have to plan to address that between releases and keep these PyO3 updates short and sweet.

I'll update the docs and push this out tonight if possible. String interning and dependency updates can come later.

**Comment by cjdsellers** [comment]
@awestlake87 apologies are unnecessary, we greatly appreciate the work you put into this project.

**Comment by cjdsellers** [comment]
🚀 many thanks!

**Pull request merged**
