### PR TITLE
update to py3 0.16

### PR DESCRIPTION
**Pull request by Igosuki**
CI shoudl be ok.
Now uses the latest pyo3 release.

### CODE REVIEW

**Comment by awestlake87** [comment]
Thanks for the PR! Ill try to get this merged and published sometime this weekend.

**Comment by awestlake87** [comment]
Sorry for the delays on this. I've been busier than I thought I'd be between work and family this week, so I'll try to get it out by next weekend!

**Comment by Igosuki** [comment]
No worries let me know when it's done I'm trying to get the whole pyo3 ecosystem to migrate to 0.16 so I can switch on my project 👍

**Comment by awestlake87** [comment]
No worries about the CI failures, I'll fix them in a combined PR. I think pyo3 removed support for Python 3.6 so that's to be expected

**Pull request merged**
